name             "lvac"
maintainer       "Mike Griffin"
maintainer_email "github@mikegriffin.ie"
license          "All rights reserved"
description      "Installs/Configures lvac"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.3.3"

depends "apt"
depends "zsh"
depends "mysql"
depends "database"
depends "nginx"
depends "php-fpm"
depends "git"
depends "vim"
